# GitHub Actions Workflow: Deploy Static Site to GitHub Pages

name: Deploy Portfolio to GitHub Pages

# Controls when the action will run. 
# Triggers the workflow on push events but only for the "main" branch.
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "deploy".
  deploy:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages.
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js. While not strictly required for a simple HTML file,
      # it's good practice for portfolios that might later include build steps (like for CSS or JS).
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Configure GitHub Pages. This action helps configure the base path correctly.
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 4: Upload the static site files as an artifact.
      # The action will automatically package all files from the root directory.
      # Your index.html should be in the root of your repository.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the directory containing the static files to be deployed.
          # '.' means the root of your repository.
          path: '.'

      # Step 5: Deploy the artifact to GitHub Pages.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
